### ISSUE TITLE
Problema na renderização das frutas

### ISSUE THREAD

**Issue by JeanB762** [nicolas-oliveira/snake#1]
Jogo muito bacana, porém tem momentos em que a frutinha deixa de aparecer, impossibilitando fazer mais pontos no jogo e tendo que reiniciar.

**Comment by nicolas-oliveira** [comment]
É uma função que é responsável pelo spawn da maçã, caso ele aleatoriamente caia em cima da snake, com exceção da cabeça, ele irá renderizar novamente, vou revisar esta parte do código e então retorno aqui.
